services:
  api:
    environment:
      - APP_ENV=${APP_ENV:-development}
      - DEBUG=true
  nginx:
    ports: !override
      - "9080:80"
  
  db:
    ports:
      - "127.0.0.1:5432:5432"