nano: Docker Security Scan
on:
  push:
    branches:
    - latihan
    pull_request:
      branches:
    - latihan

  permissions:
    contents: read
    pull-requests: read

  jobs:
    Security: 
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Run Built docker image
        run : docker built -t fastapi-crud:ci .
        
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type:image
          image-ref:fastapi-crud:ci
          format:tabel
          Security:HIGH,CRITICAL
          exit-code:`1`
          ignore-unfixed: true